name: RSS

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Install Pandoc
        run:
          sudo apt-get install -y pandoc

      - name: Replace Base Url & Build RSS
        run: |
          cd docs/
          ./script/replace_baseurl.sh
          ./script/rss.sh

      - name: Commit Updated
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "action: build pikapikapi-blog-rss.atom"
